name: Deploy Debian
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  deploy-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: tosshin

      - name: Checkout keisan dependency
        uses: actions/checkout@v4
        with:
          repository: ichiro-its/keisan
          ref: 593c9dce7acf322db4e13a3d15d628de3e7186be
          path: keisan

      - name: Build Debian package
        uses: ichiro-its/ros2-build-debian-action@main
        with:
          ros2-distro: iron
          unique-version: true

      - name: Deploy Debian package to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "package/*.deb"
          target: "~/temp/threeal/tosshin/"
          rm: true

      - name: Prepare Debian package in the server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ~/repository/debian
            reprepro includedeb threeal ~/temp/threeal/tosshin/package/*.deb
            rm -rf ~/temp/threeal/tosshin/
